version: '2'
services:
    smart-app:
        image: smart
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://smart-postgresql:5432/smart
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    smart-postgresql:
        extends:
            file: postgresql.yml
            service: smart-postgresql
